[build]
  command = "cd backend && mvn clean package -DskipTests"
  builder = "NIXPACKS"

[deploy]
  startCommand = "java -jar backend/target/*.jar"

[env]
  PORT = "8080"
  SPRING_PROFILES_ACTIVE = "production"
  JAVA_VERSION = "21"

[[services]]
  internal_port = 8080
  protocol = "TCP"

[healthchecks]
  grace_period = "30s"
  interval = "30s"
  timeout = "10s"
  restart_limit = 3
